name: Node.js Lint

on:
  push:
    branches: ["**"]
    paths:
      - 'webhook-api/**'
      - '.github/workflows/node-lint.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'webhook-api/**'
      - '.github/workflows/node-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./webhook-api

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Node.js Config
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint